### ISSUE TITLE
Add "accept" attribute support in the file <input>

### ISSUE THREAD

**Issue by jsvini** [sconsult/croppic#109]
"The `accept` attribute, limits the file selection dialog to files with certain MIME types."

So, if I want the user only be capable of select JPG files, the input should be like this:

`<input type="file" accept="image/jpeg">`

Would be great to have this option.

**Comment by sconsult** [comment]
Hi @jsvini 

Good input, however there are limitations in regards compliance with browser versions, that's why we have not integrated into the master. However there stands nothing in the way to modify the code for yourself ;-)

http://www.w3schools.com/tags/att_input_accept.asp

i have provided an alternative here:

https://github.com/sconsult/croppic/issues/36

Thanks for sharing,

Cheers

Mat
