### ISSUE TITLE
cannot drag for the full height

### ISSUE THREAD

**Issue by avalanche1** [sconsult/croppic#116]
When I drag an image from top to bottom (or vice versa) - it can be dragged maximum for the height of  the preview box. Thus I have to release the image, then re-drag it move it further.

**Comment by sconsult** [comment]
hi @avalanche1 

based on your statement i assume you would like to have the drag function beyond the maximum height of selection area. Well this is not as easy as it sounds, because you need to adapt a listener for the drag even which can go beyond the boundaries of the preview area.

This is like asking you want to see more on your screen then your screen size actually permits.

A possible approach could be to could find a way overlay the preview with a bigger div and react on that instead on the preview itself.

Having that said the effort to implement a solution which is completely browser compatible is way beyond what i would deem justifiable to resolve a "i have to release the image and reset my coursor".

if you find  a solution, dont hesitate to share it

Cheers

Mat
