### ISSUE TITLE
croppic not working in Safari after choose an image

### ISSUE THREAD

**Issue by onlinepch** [sconsult/croppic#128]
Hi, guys
I'm using croppic.js from www.croppic.net, only under Safari/Mac not working after I choose an image and click "check" for OK, it's loading.
Is there a solution for this issue?
Thanks!

**Comment by sconsult** [comment]
Hi @onlinepch 

I appreciate you have taken the time to open a Issue. However you are describing an issue, without any information on what the issue is. Not working could be literally anything.

If you could be so kind on elaborating what is not working such as:
- add information if you get console output (you need to add the callback listeners to it, especially the onError), 
- a screenshot
- Browser information
- using, meaning you are testing on croppic.net ?

Looking forward to more information

Cheers

Mat

**Comment by onlinepch** [comment]
Hi, @sconsult 

Thanks for the response, I did it !
It was some settings of Safari, it delete my session and cache, when I switch to remember them it's work fine.
Thanks for the script, it's a good one.
