### ISSUE TITLE
no handler for nginx 413 error

### ISSUE THREAD

**Issue by mrmagcore** [sconsult/croppic#130]
The code makes no provision for an ajax return status that is neither 'success' or 'error'.  In the case of an nginx 413 error (request entity too large), there is no hook to an error message.

This is in the afterUpload function.

**Comment by sconsult** [comment]
Hi @mrmagcore 

As outlined in other tickets we are working on the next release which contains a deeper error handling.
We will provide also the response back to the Callback outhority, so you can handle the error to your liking in your applicaition.

Since this is a duplicated of the same request i will close this issue. But thank you for elaborating on it, it helps to get this tool better and better.

Cheers

Mat
