### ISSUE TITLE
Is bootstrap really a dependency?

### ISSUE THREAD

**Issue by koceg** [sconsult/croppic#132]
Bootstap is listed as a dependency in a *bower.json*, but I do not use it in my current project. I can override dependencies in my *grunt-bower-concat* config, but will it break functionality in some way? (I don't care much about styling)

**Comment by sconsult** [comment]
Hi @koceg

Only for the website, with the examples. Since croppic contains also a working environment which you can run locally for testing, i have added it.

To my shame i need to acknowledge that i am not using bower personally. I have added it based on the requests i have gotten. 
I'm sure your are better qualified then me on that area, if you think it makes no sense then i will removed it.

Cheers and thanks for the question

Mat

**Comment by koceg** [comment]
What do you think about decoupling plugin and example app? It would be easier to figure things out and get started for a newcomers such as myself.
I have some free time this weekend, so I can make some refactoring and send a pull request. But it would obviously be big in terms of lines changed and it pretty soon can became outdated and out of sync with original repo.
I see some old PR hangin', so I've decided to ask first, before spending actual time on a task that might not be welcomed :)

**Comment by sconsult** [comment]
Hi @koceg 

No really understanding what you mean by decoupling. The app and the Example is decoupled, but its in one repo at github. The downloads what every person has available are the full site or just the croppic plugin. If you could elaborate what you have in mind, i'm definitively open to hear you out.
if the motivation is solely for bower, i would probably say it will become way to much effort for the goal which we would like to achieve.

There are open pull requests which i purposely leave open as reference. While i really appreciate all participation, cosmetic changes (such as uploading new buttons, or refactoring without any additional features) don't add value to the tool and are more about personal opinion.

Those i will not merge into the master, similar as add-ons which limit the browser compatibility. However as stated due to the respect and appreciation i have for all participants in this project i leave them open as reference.

I certainly dont hold you back, and encourage you tom participate with your own pull request.

Cheers
Mat

**Comment by koceg** [comment]
Well, it's not clear at first what is essential for the plugin itself and what is part of the example app and can be ignored or used as a reference. We already established that it's coupled in the bower.json, but also if we look at the /assets/css/croppic.css we can see styles for bubbling preloader. And it is not referenced in the documentation at all, it's only used in index.html. While it is a nice effect it's not vital for the plugin and I don't see any reason to keep it with plugin styles.

I disagree with you on refactoring value - it's very important part of development. Refactoring helps keeping project clean and healthy and it is much easier to spot bugs in a clean project. And it more fun to work with :)

Well, I guess I will make my suggestions and we will see what do you think about them. I hope you will at least keep an open mind :)

Thanks for the plugin, btw it's awesome :)

**Comment by sconsult** [comment]
Hi @koceg

To clarify, your talking about bower, which i already suggested you can take bootstrap out, based on your statement.
The code is decoupled in the downloads section on the croppic.net. You have 2 downloads, min and full.
Loader is documented on the HTML page (loaderHtml), however its not mandatory to have a loader, and the example is what it is, just an example, and its not part of the min download available either.

In regards to refactoring, i obviously missed to bring my point across. Refactoring for refactoring sake is useless, i have not said refactoring itself does not bring value. I also have mentioned it in the context of all the other PR which are not enhancements, but personal option contributions. From one developer to another, i believe my code is clean, but in reality you can ask 10 developers and they will suggest 10 different development guidelines and refactoring methods.

You are absolutely right about clean structured code, however going back for what this topic was all about "is bootstrap really a dependency". This is solely a bower config issue, and now you are talking about changing a lot of things which are already there, just not where you want it to be ;-)

Similar as you asked me to keep an open mind, ask yourself what is personal taste and what is worth the effort to change everything just for change sake. So far you are the first person elaborating on that issue (which is much appreciated), so the issue we are discussing here looks marginal from my point of view.

I have only one criteria for pr's, which is development effort needs to bring the tool ahead. Ease of use, new feature, better integration, you name it and never, ever forget backwards compatibility.

I will look forward to your contribution.

Cheers

Mat

**Comment by sconsult** [comment]
@koceg 

As per your request bootstrap has been removed as dependency in todays update

Mat

**Comment by koceg** [comment]
@sconsult, thanks, sorry I didn't respond to your last message.
