### ISSUE TITLE
Simple Request.

### ISSUE THREAD

**Issue by clostastic** [sconsult/croppic#137]
I have very little knowledge about all this but my needs from croppic are very simple so I hope someone will take the time to point me in the right direction. I will try to be concise and to the point.

everything works fine up until the part where i hit the green crop button at this point the three circle animation comes and and keeps repeating over and over again.

For my use all i want is for the image to update on the webpage and no further functionality from that point on...no actual upload or save to server or anything like that. because am overlaying a .png over the cropped image. Like a "virtual try on" 

ps I am using google app engine hosting because I am cheap and i like to fiddle before I commit to purchasing hosting service so it could just be a limitation of that. 

any help is greatly appreciated

![screen shot 2015-07-10 at 8 38 43 am](https://cloud.githubusercontent.com/assets/13274841/8620060/a681ed36-26e2-11e5-804b-480ebc7bc979.png)
this is a screen shot of the result after pushing the green crop button the animation just keeps repeating I want the crop to take and no further action.

**Comment by sconsult** [comment]
Hi @clostastic 

This symptoms are described a lot of times. Most likely it points to either your apache, doesnt allow the large picture uploads, or you dont have appropriet permissions.

If you look through the closed tickets, you will find the solution if its one of the two above mentioned.

You have the abillity to add a callback listener to your script (on error). You should get a feedback on what the issue is.

Mat

**Comment by silantevas** [comment]
nice guy :)

**Comment by sconsult** [comment]
@clostastic  

Where you able to get the problem resolved, or can you share the output of your console here ?

**Comment by sconsult** [comment]
no response received
