### ISSUE TITLE
Draggin not work actually on Chrome  44.0.2403.130 (64-bit)

### ISSUE THREAD

**Issue by delirehberi** [sconsult/croppic#151]
Somewheres in pages, croppic drag not work. 

Detailed video in here [https://www.youtube.com/watch?v=T3-lM6iaVK0&feature=youtu.be](https://www.youtube.com/watch?v=T3-lM6iaVK0&feature=youtu.be)

**Comment by sconsult** [comment]
Hi @delirehberi 

Thanks for the vid documentation, this is extremely helpful.
Will look into it.

Mat

**Comment by sconsult** [comment]
Hi @delirehberi

After intense testing my team was still not able to replicate your issue. Its very well documented, i wish all tickets would have this kind of feedback. 

Having that said, could it be that other code on your page interferes with croppic or there is a memory related issue? Since we cant replicate it i need to assume it has something to do with your environment. 

We have flagged this issue, so if its getting reported again we can take another stab at it.

Cheers

Mat

**Comment by delirehberi** [comment]
Thanks for effort. 

I was changed design modalbox to single page. All crop actions moved to another page and issue fixed for me. 

Best regards.

**Comment by sconsult** [comment]
Hi @delirehberi 

Thanks for the feedback, appreciate it.

Cheers

Mat
