### ISSUE TITLE
anyway to change cropping image after initilization

### ISSUE THREAD

**Issue by jangidgirish** [sconsult/croppic#182]
is there anyway to change image after initializing Croppic??
I have 4 images on page, so i want to switch image on button click from existing four images then crop image.
can you please suggest how to implement it from croppic plugin

**Comment by sconsult** [comment]
hi @jangidgirish 

Yes there is a workaround to get this done

Implement the callback you want to react to in the cropper options. As example:

onReset:function(){ console.log('onReset') },\

The example above is called when the user clicks on the X.
Instead of writing the to the console as in the example above, reinstatement the croppic with your new picture and voila....you have your next picture loaded.

Mat

**Comment by jangidgirish** [comment]
thank you for reply, i have worked around with *destroy()* and *init()* methods, working fine
```
cropperHeader.destroy();
cropperHeader.options.loadPicture = data.imagePath;
cropperHeader.init();
```
