### ISSUE TITLE
Possible causes for cropic being stuck on load 

### ISSUE THREAD

**Issue by bradkyle** [sconsult/croppic#197]
I currently am experiencing a problem whereby my croppic image cropper is stuck on loading.
I am unsure of the cause of this however I was hoping that I could find some assistance here.
Are there any possible causes that you may know of that I could remedy?
Thanks for your time.

**Comment by sconsult** [comment]
This could be a variete of Issues. In order to troubleshoot this issue, you would need to attache the error listener to the croppic, and paste the error you are seeing in the browser console:

Attaching the listener:

onError:function(errormessage){ console.log('onError:'+errormessage) }

In most cases this is related to the server not beeing properly configured. (PHP max file upload size as example)
If you look through the closed tickets, you will find several entries to that topic.
