### ISSUE TITLE
Minimum width and height of uploaded image

### ISSUE THREAD

**Issue by baerni** [sconsult/croppic#208]
Hi. It is possible to check width and height of uploaded image and alert when it is too small?

**Comment by sconsult** [comment]
yes, you would need to modif https://github.com/sconsult/croppic/blob/master/img_save_to_file.php in order to check for file dimensions there, and could throw and error.

If you are using the InlineProcess feature which utlizes the FileReader API,  this link might help you to get it implemented:

http://stackoverflow.com/questions/15491193/getting-width-height-of-an-image-with-filereader

Cheers

Mat
