### ISSUE TITLE
Safari problems

### ISSUE THREAD

**Issue by rezoanulalamriad** [sconsult/croppic#211]
Following problems in safari:
1. Image become distorted after upload. But in chrome, firefox same image is not distorted.
2. Delete button is not working.

Thanks,
Riad.

**Comment by sconsult** [comment]
Hi Riad,

Thank you for your ticket. I need to repeat. without having any clue what your seeing i will not be investing time, if your not investing time to add requested information to the ticket:

Explicitly i requested:

Screenshot of what your seeing
Browser version you are using

Did you add the error log output to the browser console ? if yes what is the output ?

Cheers

Mat

**Comment by rezoanulalamriad** [comment]
This is the image distorted in safari 
![image](https://cloud.githubusercontent.com/assets/8417136/13929753/f3f4631c-efc5-11e5-8b06-371f99e15e1b.png)

And then delete button not working in safari

**Comment by rezoanulalamriad** [comment]
Hi Matt,

Do you get the info now ?

Thanking,
Riad.

**Comment by sconsult** [comment]
Hi Riad,

We are getting somewhere, however did you read my message above ?

"Did you add the error log output to the browser console ? if yes what is the output ?"

Mat

**Comment by rezoanulalamriad** [comment]
HI Mat,

Unfortunately no. No Message or log. 

Riad.

**Comment by sconsult** [comment]
Hi Riad,

I see the distorted picture you have uploaded, however i cannot replicate your issue.

In order to help you you would need to be a little bit more forthcoming with information.

How you initialize croppic, is it part of another implementation, server logs or error reporting.

Here is what you need to perform at minimum:

Add into your configuration the Callback onError (you can see an example in the docs for CALLBACKS on croppic.net)

onError:		function(errormsg){ console.log('onError:'+errormsg) 

after you have added this open safari and access the console:

To access the developer console in Safari, use the Develop > Show Error Console menu item (Option-Cmd-C): If you don't see the Develop menu, you'll need to turn it on using Safari Preferences. Open Safari > Preferences, and click on the Advanced Tab.

Please perform after that the whole process again, and upload any feedback you receive in the console yo this ticket.

Please look also in your server logs for any output related to croppic and add it to this ticket.

Please also add if you see the same problem on croppic.net AND your own implementation.

Your stating your having this issue on your safari version, did you check for updates, or check on another MAC/PC if you can replicate the issue ?

As more information you can provide as better anybody can help you

Mat

**Comment by rezoanulalamriad** [comment]
Hi Mat,

Thanks for your email. Basically, I am a windows user. I don't have a mac. I was trying to install mac in virtual box but it didn't go through. The problem is happening for our CEO. In her iPad or Mac may be.
So, could you advise please how can I do this when I don't have a mac. Because this is very technical for our CEO.

Thanking, 
Riad.

**Comment by rezoanulalamriad** [comment]
Hi Mat,

Do you have an answer for me ?

Riad.

**Comment by sconsult** [comment]
Riad,

With all due respect, i don't. You need to address your CEO's issue with your companies tech support. This is an open source library with voluntary support and i am absolutely willing to help out wherever i can, however to expect to troubleshoot your CEO's Issues is really not even close in the scope of what your realistically can expect from any open source product.

If your tech support can provide further information then please have them open a new ticket, i will close this one as way-out-of-scope.

Mat

**Comment by ghost** [comment]
Hi Mat,

Sorry I'm posting to a closed ticket.
What if I give you the access to our site so that you can see the error yourself?
Please let me know, thanks.

Riad.
