### ISSUE TITLE
croppic broken when other js using strict mode

### ISSUE THREAD

**Issue by kavin-90** [sconsult/croppic#219]
croppic does not work with other jquery plugins which is using strict mode it return default options but not use defined options any help will be help

It works with jquery latest correctly without any problem.

**Comment by marcosschroh** [comment]
Ph c h

**Comment by marcosschroh** [comment]
Ph c h
El 26/4/2016 5:14 a. m., "kavin-90" notifications@github.com escribió:

croppic does not work with other jquery plugins which is using strict mode
it return default options but not use defined options any help will be help

It works with 2.2.3 correctly without any problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/sconsult/croppic/issues/219

**Comment by kavin-90** [comment]
Its works now so Everything is okay now That's why i closed issue
