### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by kibray** [sconsult/croppic#40]
Hi to everybody,

I just downloaded the script and built in a very simple html page...but I get this error in console:
Uncaught SyntaxError: Unexpected token < jquery-1.10.2.js:550

here is my code:
<style>
        #yourId{
            width: 400px;
            height: 400px;
            position: relative;
            border: 1px solid black;
        }
    </style>
<body>
<div id="yourId"></div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="croppic.min.js"></script>
<script>
    var cropperHeader = new Croppic('yourId');
    var cropperHeader = new Croppic('yourId', cropperOptions);

    var cropperOptions = {
        customUploadButtonId:'myDivId',
        modal:true,
        uploadUrl:'img_save_to_file.php',
        cropUrl:'img_crop_to_file.php'
    }
</script>

Any idea what I'm doing wrong?!

Thank you in advance
Marco

**Comment by rotherfuchs** [comment]
@asaadmahmood could you give some more details on how you solved it?

**Comment by sconsult** [comment]
Hi @rotherfuchs

This problem was related to issues concerning the two php files. If the files where to large, the server was out of memory/bandwith or similar issue the error handling was not properly solved.

This problem has been addressed in a release in february, if you have a similar problem please open an new Issue and i will try to help you through it.

Cheers

Mat

**Comment by vicmg11** [comment]
Did you figure it out, I am still getting the same error. @kibray
