### ISSUE TITLE
transparent images get black background

### ISSUE THREAD

**Issue by maximl337** [sconsult/croppic#77]
Is there anyway to make png transparent images retain transparency or have a white background?

**Comment by sconsult** [comment]
Hi Maximl337,

The Scripts which are delivered with croppic are simple examples and should NOT be used in production. Since you want to have a good quality i recommend to rewirte the script to work with imagemagick or any other high quality image processing library.

But here is what you can do immediately:

The file img_crop_to_file.php is by default delivering the file as jpg, thats why you have always a black background.

You would need to change the script to png.
Look for the following line and uncomment this:

//imagepng($final_image, $output_filename.$type, $png_quality);

and comment this:
imagejpeg($final_image, $output_filename.$type, $jpeg_quality);

Cheers

Mat

**Comment by maximl337** [comment]
Hi thanks for the reply. That worked with one tweak:

after this line:

$final_image = imagecreatetruecolor($cropW, $cropH);

I had to add: 

imagealphablending($final_image, false);

imagesavealpha($final_image, true);

this retains transparency.

**Comment by sconsult** [comment]
Hi maximl,

Excellent, thank you for sharing the code, i will have the examples updated.

Cheers

Mat

**Comment by techyogi7** [comment]
Hello maximl,

Your answer worked for me too but cropped image gets black rough edges I tried to set $png_quality from 1-9 but won't worked out for me.

is there anything else i have to do for that??

Thanks,
Yogo
