### ISSUE TITLE
Bower asset

### ISSUE THREAD

**Issue by sciolini** [sconsult/croppic#79]
Hi, could you add bower.json file in the repository and register the package in http://bower.io/. Is very simple (http://bower.io/docs/creating-packages/) and help us to use it in different proyects.

Thanks

**Comment by sconsult** [comment]
Will look into it.

Mat

**Comment by johnbacon** [comment]
+1

**Comment by Sander-Toonen** [comment]
+1

Being available on Bower is essential to us.

**Comment by czarpino** [comment]
+1

**Comment by sconsult** [comment]
Bower support has been added

Package:

https://libraries.io/bower/croppic

Install tags:

bower install croppic

Since i really don't use bower in my projects, please let me know if there should be any excludes added, or any other suggested changes.

Cheers and Thanks in advance for your feedback

Mat
