### ISSUE TITLE
Passing parameters through php page

### ISSUE THREAD

**Issue by kumarsravan031** [sconsult/croppic#84]
How can i pass parameters to php page through this plugin. something like
$.post('sample.php',{parameter: value},function(){.............}) 
where as in croppic php page is sent like
var cropperOptions = {
	cropUrl:'path_to_your_image_cropping_file.php'
}

**Comment by mmarif4u** [comment]
Maybe this could help:
`cropData:{
				"dummyData":1,
				"dummyData2":"text"
			}`
Just put inside the cropperOptions var.
http://www.croppic.net/ documentation has more about this(cropData).

**Comment by sconsult** [comment]
Hi @kumarsravan031,

Did cropData not work for you, or why did you reopen the issue ? @mmarif4u info is correct.

Mat

**Comment by kumarsravan031** [comment]
Hi @sconsult  
Yes info is correct. One more problem, This is the code im using
var croppicHeaderOptions = {
				doubleZoomControls:false,
				rotateControls:false,
				cropUrl:'ImageUpload.php',
				cropData:{
					"ID":localStorage.getItem('resId'),
					"token":localStorage.getItem('token')
				},
				uploadUrl:'ImageProcessing.php',
				uploadData:{
					"ResRegID":localStorage.getItem('resId'),
					"token":localStorage.getItem('token'),
					"imgurl":imgUrl,
					"imgx":imgX1,
					"imgy":imgY1,
					"croph":cropH,
					"cropw":cropW
				},
				customUploadButtonId:'cropContainerHeaderButton',
				modal:false,
				imgEyecandy:true,
				imgEyecandyOpacity:0,
				processInline:true,
				loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
				onBeforeImgUpload: function(){ console.log('onBeforeImgUpload') },
				onAfterImgUpload: function(){ console.log('afterImageUpload') },
				onImgDrag: function(){ console.log('onImgDrag') },
				onImgZoom: function(){ console.log('onImgZoom') },
				onBeforeImgCrop: function(){ console.log('onBeforeImgCrop') },
				onAfterImgCrop:function(){console.log('onAfterImgCrop') },
				onError:function(errormessage){ console.log('onError:'+errormessage) }
		}	
		var croppic = new Croppic('croppic', croppicHeaderOptions);

After the image is uploaded it is displaying for a second and it is disappearing getting into the default upload position,
and how can i get the imgUrl,imgX1,imgY1,cropH,cropW value after the image is uploaded.
Thanks in advance.

**Comment by sconsult** [comment]
Hi @kumarsravan031

I'm not sure if i understand what your trying to say here:

"After the image is uploaded it is displaying for a second and it is disappearing getting into the default upload position"

Taking a guess, the best way to access information at a certain point are through the callbacks.
In the example on the website we are using a simple log output. You need to register a callback as a croppicHeaderOptions.

onAfterImgUpload: 	function(){ console.log('onAfterImgUpload') },

in your example you just want to access the croppic object instead of console.log

Mat

**Comment by kumarsravan031** [comment]
You will be receiving the following data via AJAX POST method as multipart/form-data; 
(note that ajax is limited to same domain requests)

	imgUrl 		// your image path (the one we recieved after successfull upload)
				
	imgInitW  	// your image original width (the one we recieved after upload)
	imgInitH 	// your image original height (the one we recieved after upload)

	imgW 		// your new scaled image width
	imgH 		// your new scaled image height

	imgX1 		// top left corner of the cropped image in relation to scaled image
	imgY1 		// top left corner of the cropped image in relation to scaled image

	cropW 		// cropped image width
	cropH 		// cropped image height

how can i get these value after upload, i mean can we those value in console?

**Comment by sconsult** [comment]
Hi kumarsravan031 

The Statement "data isnt passing to the server" is very broad is im not sure what you are trying to achieve or if the problem is with calling your ImageUpload.php, resp. the ImageProcessing.php

you can see in the current code, that uploadData is appended to formdata, which is submitted with the uploadUrl provided.

formData = new FormData(that.form[0]);
				
for (var key in that.options.uploadData) {
	if( that.options.uploadData.hasOwnProperty(key) ) {
		formData.append( key , that.options.uploadData[key] );	
	}
}										
					
$.ajax({
	url: that.options.uploadUrl,
	data: formData,
	context: document.body,
	cache: false,
	contentType: false,
	processData: false,
	type: 'POST'
}).always(function (data) {
	that.afterUpload(data);
});

How do you handle the variable on PHP side ? Can you post some code ?

Mat

**Comment by sconsult** [comment]
no response received
